# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 11
  - name: Publications
    url: /#publications
    weight: 12
  - name: Projects
    url: projects/
    weight: 13
  - name: Sdudents
    url: students/
    weight: 14
  - name: Courses
    url: courses/
    weight: 15
  - name: OperatingSystem
    parent: Courses
    url: courses/OperatingSystem
    weight: 10  
  - name: BigDataStorage
    parent: Courses
    url: courses/BigDataStorage
    weight: 11
  - name: Library
    url: library/
    weight: 16
  - name: Contact
    url: /#contact
    weight: 17