# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    identifier: 7fe3f2c3
    url: /
    weight: 10
  - name: 新闻
    identifier: 8b8adace
    url: /#news
    weight: 20
  - name: 论文
    identifier: 1457d86a
    url: /#publications
    weight: 30
  - name: 项目
    identifier: bd14aecb
    url: projects/
    weight: 40
  - name: 指导学生
    identifier: 082d2e2a
    url: students/
    weight: 50
  - name: 教学
    identifier: 6252ddc8
    url: courses/
    weight: 60
  - name: 智能审计
    identifier: 7159b954
    url: /courses/ai-audit
    weight: 61
    parent: 6252ddc8
  - name: 大数据存储
    identifier: e417f315
    url: /courses/bigdatastorage
    weight: 62
    parent: 6252ddc8
  - name: 操作系统
    identifier: 10dd7978
    url: /courses/operatingsystem
    weight: 63
    parent: 6252ddc8
  - name: 搜索
    identifier: df9e6afc
    url: library/
    weight: 70
  - name: 联系方式
    identifier: 7bb31687
    url: /#contact
    weight: 80
